baseURL = "https://texify2.io"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = ""
hasCJKLanguage = true
languageCode = "en"
paginate = 5
rssLimit = 10
theme = "hugo-texify2"
title = "TeXify2"

[author]
email = "me@example.com"
name = "Pavel Sapezhka"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "tango"

[[menu.main]]
identifier = "post"
name = "Post"
url = "/"
weight = 1
[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/post/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
series = "series"
tags = "tags"

#########################
# TEXIFY2 THEME OPTIONS #
#########################

[params]
description = "An example site for hugo theme TeXify2"
favicon = "favicon.ico"
footnote = """
Follow me on <a class=link href=https://github.com/weastur target=_blank rel=noopener>GitHub</a>,
<a class=link href=https://www.linkedin.com/in/weastur/ target=_blank rel=noopener>LinkedIn</a> or
<a class=link href=/index.xml>RSS</a> |
<a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en target=_blank rel=noopener>CC BY-NC-SA 4.0</a>
"""
keywords = ["hugo", "latex", "theme"]
customCSS = []
customJS = []
dateFormat = "January 2, 2006"
fullTextRSS = true
emphasisWithDots = true
since = "2023"
toc = false
showWordCount = true
showReadingTime = true

[params.math]
enable = false
use = "katex"

[params.outdated]
enable = false
limit = 1000
warning = "⚠️ It has been <i>%d</i> days since the last update, the content of the article may be outdated."

# https://giscus.app
[params.giscus]
enable = false
script = """
"""

# https://utteranc.es
[params.utterances]
enable = false # whether to enable utterances
# paste utterances' <script></script> configuration between the triple quotes
script = """
"""
