name = "TeXify3-minimal-blog"
license = "MIT"
licenselink = "https://github.com/AlphaGergedan/minimalistic-hugo-blog-theme/blob/master/LICENSE"
description = "Modified TeXify3 for my minimalistic personal blog page."

homepage = "https://github.com/AlphaGergedan/minimalistic-hugo-blog-theme"

demosite = "https://michaelneuper.github.io/hugo-texify3/"

tags = ["blog", "clean", "latex", "light", "minimal", "responsive", "simple"]
features = ["blog", "postcss", "comments", "google analytics"]

[author]
    name = "Atamert Rahma"
    repo = "https://github.com/AlphaGergedan/minimalistic-hugo-blog-theme"

[original]
    name = "Michael Neuper"
    homepage = "https://michaelneuper.com"

