baseURL = "https://texify2.io"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = ""
hasCJKLanguage = true
ganguageCode = "en"
paginate = 5
rssLimit = 10
theme = "hugo-texify2"
title = "TeXify2"

[author]
email = "me@weastur.com"
name = "Pavel Sapezhka"

[params.commentEngine]
code = """
"""

[params.buymeacoffee]
code = """
<script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="weastur" data-description="Support me on Buy me a coffee!" data-message="" data-color="#FF5F5F" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
"""
