name: Build with Hugo
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - 'latest'
          - '0.113.0'
    steps:
      - uses: actions/checkout@v3
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true
      - name: Run
        run: hugo --config=exampleSite/config.toml --contentDir=exampleSite/content --themesDir=..
